version: '3'

services: 
    app:
        image: jksantos/fcd-image-laravel:latest
        build: .docker/PHP
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s php-fpm
        container_name: app
        networks: 
            - laravel-network
        volumes: 
            - .:/var/www
        depends_on: 
            - mysql
            - redis
        
    mysql:
        image: mysql:5.7
        networks: 
            - laravel-network
        ports: 
            - "3303:3306"
        command: --innodb-use-native-aio=0
        volumes: 
            - .docker/mysql/dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root

    redis:
        image: redis:alpine
        expose: 
            - 6397
        networks: 
            - laravel-network

    nginx:
        build: .docker/nginx
        container_name: nginx
        entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
        restart: always
        tty: true
        ports: 
            - "8000:80"
        networks: 
            - laravel-network
        volumes: 
            - .:/var/www
        environment: 
            - HOST_APP=app
            - PORT_APP=9000
        depends_on: 
            - app

networks: 
    laravel-network:
        driver: bridge
